version: "3.8"

services:
  frontend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
      target: dev
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "5173:5173"
    volumes:
      - ../src:/app/src:delegated
    healthcheck:
      test: "curl -f http://localhost:5173 || exit 1"
      interval: 5s
      timeout: 30s
      start_period: 20s

  test:
    build:
      context: ../
      dockerfile: infra/Dockerfile
      target: dev
    volumes:
      - ../:/app:delegated
    command: ["npm", "test", "--ci", ""]
