version: "3.8"

services:
  frontend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    ports:
      - "5173:5173"
    healthcheck:
      test: "curl -f http://localhost:5173 || exit 1"
      interval: 5s
      timeout: 30s
      start_period: 20s
