version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 5s
      timeout: 30s
      start_period: 20s
