# cspell:words cimg
version: 2.1

jobs:
  app-test:
    docker:
      - image: cimg/node:18.13.0

    steps:
      - checkout
      - run: npm install
      - run: make test

workflows:
  app-workflow:
    jobs:
      - app-test
