# cspell:words cimg lcov
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

workflows:
  app-workflow:
    jobs:
      - app-test
      - aws-test:
          context:
            - aws
            - test

jobs:
  app-test:
    docker:
      - image: cimg/node:18.13.0

    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume_role_with_web_identity:
          role_arn: ${AWS_ROLE_ARN}
      - run:
        name: Create credentials file
        command: |
          mkdir -p ~/.aws
          cat <<EOL > ~/.aws/credentials
          [default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
          aws_session_token = ${AWS_SESSION_TOKEN}
          EOL
      - run:
          name: Create config
          command: |
            mkdir -p ~/.aws
            cat <<EOL > ~/.aws/config
            [profile default]
            region = ${AWS_REGION}
            output = json
            EOL
      - run: npm install
      - run: amplify pull
      - run: make ci-test
      - run: |
          mkdir -p ./reports/eslint/
          make ci-eslint
      - store_test_results:
          path: ./reports/
