# cspell:words cimg lcov
version: 2.1

jobs:
  app-test:
    docker:
      - image: cimg/node:18.13.0

    steps:
      - checkout
      - run: npm install
      - run: make ci-test
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage_report

workflows:
  app-workflow:
    jobs:
      - app-test
