# cspell:words cimg
version: 2.1

jobs:
  app-build:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - checkout
      - run: make app-build

workflows:
  app-workflow:
    jobs:
      - app-build
