# cspell:words cimg lcov
version: 2.1

jobs:
  app-test:
    docker:
      - image: cimg/node:18.13.0

    steps:
      - checkout
      - run: npm install
      - run: make ci-test
      - store_test_results:
          path: coverage/

workflows:
  app-workflow:
    jobs:
      - app-test
