version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    env_file: devcontainer.env

    environment:
      APP_BASE_PATH: http://localhost:3000

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    networks:
      - default
      - garaku-shared-network

networks:
  garaku-shared-network:
    external: true
